version: 2.1

jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.1
    steps:
      - checkout
      - run:
          name: Restore Packages
          command:
            dotnet restore
          working_directory: LibertyFamilySystem
      - run:
          name: Build
          command: dotnet build -c Release
          working_directory: LibertyFamilySystem
      - run:
          name: Running Tests
          command: dotnet test
          working_directory: LibertyFamilySystem.Test
      - run:
          name: "Build and push Docker image"
          command: |
            docker build -t LibertyFamilySystem .
            echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
            docker tag boku herocod3r/MyProject
            docker push herocod3r/MyProject